[package]
name = "rust_roguelike_tutorial"
version = "0.1.0"
authors = ["Tomasz Sterna <tomek@sterna.link>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rltk = { version = "0.8.0" }
legion = { version = "*", path = "../legion" }
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
